export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCESSS = 'ADD_COMMENT_SUCESSS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const ADD_COMMENT_RESET = 'ADD_COMMENT_RESET';

export const ADD_REPLY_REQUEST = 'ADD_REPLY_REQUEST';
export const ADD_REPLY_SUCESSS = 'ADD_REPLY_SUCESSS';
export const ADD_REPLY_FAIL = 'ADD_REPLY_FAIL';
export const ADD_REPLY_RESET = 'ADD_REPLY_RESET';

export const FETCH_COMMENT_REQUEST = 'FETCH_COMMENT_REQUEST';
export const FETCH_COMMENT_SUCESSS = 'FETCH_COMMENT_SUCESSS';
export const FETCH_COMMENT_FAIL = 'FETCH_COMMENT_FAIL';
export const FETCH_COMMENT_RESET = 'FETCH_COMMENT_RESET';