export const SEND_UPVOTE_NOTIFICATION_REQUEST = 'SEND_UPVOTE_NOTIFICATION_REQUEST';
export const SEND_UPVOTE_NOTIFICATION_SUCCESS = 'SEND_UPVOTE_NOTIFICATION_SUCCESS';
export const SEND_UPVOTE_NOTIFICATION_FAIL = 'SEND_UPVOTE_NOTIFICATION_FAIL';
export const SEND_UPVOTE_NOTIFICATION_RESET = 'SEND_UPVOTE_NOTIFICATION_RESET';

export const REMOVE_UPVOTE_NOTIFICATION_REQUEST = 'REMOVE_UPVOTE_NOTIFICATION_REQUEST';
export const REMOVE_UPVOTE_NOTIFICATION_SUCCESS = 'REMOVE_UPVOTE_NOTIFICATION_SUCCESS';
export const REMOVE_UPVOTE_NOTIFICATION_FAIL = 'REMOVE_UPVOTE_NOTIFICATION_FAIL';
export const REMOVE_UPVOTE_NOTIFICATION_RESET = 'REMOVE_UPVOTE_NOTIFICATION_RESET';

export const READ_ALL_NOTIFICATION_REQUEST = 'READ_ALL_NOTIFICATION_REQUEST';
export const READ_ALL_NOTIFICATION_SUCCESS = 'READ_ALL_NOTIFICATION_SUCCESS';
export const READ_ALL_NOTIFICATION_FAIL = 'READ_ALL_NOTIFICATION_FAIL';
export const READ_ALL_NOTIFICATION_RESET = 'READ_ALL_NOTIFICATION_RESET';

export const SEND_FOLLOW_NOTIFICATION_REQUEST = 'SEND_FOLLOW_NOTIFICATION_REQUEST';
export const SEND_FOLLOW_NOTIFICATION_SUCCESS = 'SEND_FOLLOW_NOTIFICATION_SUCCESS';
export const SEND_FOLLOW_NOTIFICATION_FAIL = 'SEND_FOLLOW_NOTIFICATION_FAIL';
export const SEND_FOLLOW_NOTIFICATION_RESET = 'SEND_FOLLOW_NOTIFICATION_RESET';