export const SEND_UPVOTE_NOTIFICATION_REQUEST = 'SEND_UPVOTE_NOTIFICATION_REQUEST';
export const SEND_UPVOTE_NOTIFICATION_SUCCESS = 'SEND_UPVOTE_NOTIFICATION_SUCCESS';
export const SEND_UPVOTE_NOTIFICATION_FAIL = 'SEND_UPVOTE_NOTIFICATION_FAIL';
export const SEND_UPVOTE_NOTIFICATION_RESET = 'SEND_UPVOTE_NOTIFICATION_RESET';