export const ADD_RECOMMEND_LIST_REQUEST = 'ADD_RECOMMEND_LIST_REQUEST';
export const ADD_RECOMMEND_LIST_SUCCESS = 'ADD_RECOMMEND_LIST_SUCCESS';
export const ADD_RECOMMEND_LIST_FAIL = 'ADD_RECOMMEND_LIST_FAIL';


export const FETCH_USERS_RECOMMEND_LIST_REQUEST = 'FETCH_USERS_RECOMMEND_LIST_REQUEST';
export const FETCH_USERS_RECOMMEND_LIST_SUCCESS = 'FETCH_USERS_RECOMMEND_LIST_SUCCESS';
export const FETCH_USERS_RECOMMEND_LIST_FAIL = 'FETCH_USERS_RECOMMEND_LIST_FAIL';
export const FETCH_USERS_RECOMMEND_LIST_RESET = 'FETCH_USERS_RECOMMEND_LIST_RESET';
