export const ADD_RECOMMEND_LIST_REQUEST = 'ADD_RECOMMEND_LIST_REQUEST';
export const ADD_RECOMMEND_LIST_SUCCESS = 'ADD_RECOMMEND_LIST_SUCCESS';
export const ADD_RECOMMEND_LIST_FAIL = 'ADD_RECOMMEND_LIST_FAIL';

export const FETCH_MY_RECOMMEND_LIST_REQUEST = 'FETCH_MY_RECOMMEND_LIST_REQUEST';
export const FETCH_MY_RECOMMEND_LIST_SUCCESS = 'FETCH_MY_RECOMMEND_LIST_SUCCESS';
export const FETCH_MY_RECOMMEND_LIST_FAIL = 'FETCH_MY_RECOMMEND_LIST_FAIL';
export const FETCH_MY_RECOMMEND_LIST_RESET = 'FETCH_MY_RECOMMEND_LIST_RESET';

export const FETCH_USER_RECOMMEND_LIST_REQUEST = 'FETCH_USER_RECOMMEND_LIST_REQUEST';
export const FETCH_USER_RECOMMEND_LIST_SUCCESS = 'FETCH_USER_RECOMMEND_LIST_SUCCESS';
export const FETCH_USER_RECOMMEND_LIST_FAIL = 'FETCH_USER_RECOMMEND_LIST_FAIL';
export const FETCH_USER_RECOMMEND_LIST_RESET = 'FETCH_USER_RECOMMEND_LIST_RESET';
