export const ADD_RECOMMEND_LIST_REQUEST = 'ADD_RECOMMEND_LIST_REQUEST';
export const ADD_RECOMMEND_LIST_SUCCESS = 'ADD_RECOMMEND_LIST_SUCCESS';
export const ADD_RECOMMEND_LIST_FAIL = 'ADD_RECOMMEND_LIST_FAIL';
