export const SEARCH_PROFILE_REQUEST = 'SEARCH_PROFILE_REQUEST';
export const SEARCH_PROFILE_SUCCESS = 'SEARCH_PROFILE_SUCCESS';
export const SEARCH_PROFILE_FAIL = 'SEARCH_PROFILE_FAIL';
export const SEARCH_PROFILE_RESET = 'SEARCH_PROFILE_RESET';