export const MY_TIMELINE_REQUEST = 'MY_TIMELINE_REQUEST';
export const MY_TIMELINE_SUCCESS = 'MY_TIMELINE_SUCCESS';
export const MY_TIMELINE_FAIL = 'MY_TIMELINE_FAIL';
export const MY_TIMELINE_RESET = 'MY_TIMELINE_RESET';