export const USER_SESSION_REQUEST = 'USER_SESSION_REQUEST'
export const USER_SESSION_SUCCESS = 'USER_SESSION_SUCCESS'
export const USER_SESSION_FAIL = 'USER_SESSION_FAIL'
export const USER_SESSION_RESET = 'USER_SESSION_RESET'