export const MY_SESSION_REQUEST = 'MY_SESSION_REQUEST';
export const MY_SESSION_SUCCESS = 'MY_SESSION_SUCCESS';
export const MY_SESSION_FAIL = 'MY_SESSION_FAIL';
export const MY_SESSION_RESET = 'MY_SESSION_RESET';

export const USER_PROFILE_TOGGLE_REQUEST = 'USER_PROFILE_TOGGLE_REQUEST';
export const USER_PROFILE_TOGGLE_RESET = 'USER_PROFILE_TOGGLE_RESET';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET';