export const USER_SESSION_REQUEST = 'USER_SESSION_REQUEST';
export const USER_SESSION_SUCCESS = 'USER_SESSION_SUCCESS';
export const USER_SESSION_FAIL = 'USER_SESSION_FAIL';
export const USER_SESSION_RESET = 'USER_SESSION_RESET';

export const USER_PROFILE_TOGGLE_REQUEST = 'USER_PROFILE_TOGGLE_REQUEST';
export const USER_PROFILE_TOGGLE_RESET = 'USER_PROFILE_TOGGLE_RESET';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
